name = "distribuidora-cimento"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "86390cc9f39d425f8e66de3581e21745"
