-- Painel admin: autenticação Supabase Auth + tabela public.admins
-- Ver scripts/009_admins_supabase_auth.sql para criar a tabela e RLS.
--
-- Fluxo típico:
-- 1) Criar usuário em Authentication (Supabase) ou via cadastro loja.
-- 2) INSERT INTO public.admins (id, email, role) VALUES (auth_user_uuid, 'email', 'admin');
-- 3) Login em /admin/login usa POST /api/auth/login com { "scope": "admin", ... } (feito pelo app).
